---
title: "King St Baselines"
author: "Aakash Harpalani"
date: "Thursday, January 25, 2018"
output: github_document
---

### Setup

Loading libraries:
```{r, message=FALSE, warning=FALSE}
library(RPostgreSQL)
library(ggplot2)
library(lubridate)
library(dplyr)
```

Establishing connections and credentials:
```{r}
drv <- dbDriver("PostgreSQL")
source("connect/connect.R")
```

### Analysis

Retrieve 15-min count data:
```{r}

strSQL <-
  paste0("SELECT intersection_name, EXTRACT(hour FROM time_bin) AS hr, SUM(eastbound) AS eastbound, SUM(westbound) AS westbound from aharpal.king_baselines_agg GROUP BY intersection_name, EXTRACT(hour from time_bin) ORDER BY intersection_name, EXTRACT(hour from time_bin)")
data <- dbGetQuery(con, strSQL)
```

Modify/Add Fields
```{r}
data$hr <- sprintf("%02d",data$hr)
data$time_bin <- as.POSIXct(data$hr, format = "%H")


lims <- as.POSIXct(c("0","3","6","9","12","15","18","21","24"),format="%H")


eb_text <- data %>%
  filter(time_bin == max(data$time_bin)) %>%
  select(intersection_name, eastbound)

wb_text <- data %>%
  filter(time_bin == max(data$time_bin)) %>%
  select(intersection_name, westbound)
```

Plot all direction/leg combinations (Adelaide and Bathurst):
```{r, fig.width= 10, fig.height = 10}

daily_plot <-
  ggplot(data = data, aes(x=time_bin, y=total_volume)) +
        annotate("rect",xmin=as.POSIXlt("07",format = "%H"), xmax=as.POSIXlt("19",format="%H"),ymin = 0, ymax=Inf, alpha = 0.15) +
       # annotate("rect",xmin=as.POSIXlt("17",format = "%H"), xmax=as.POSIXlt("18",format="%H"),ymin = 0, ymax=Inf, alpha = 0.15) +
      annotate("text",x=as.POSIXlt("13:00",format = "%H:%M"), y = 10, label = "7 a.m. to 7 p.m.", color = "darkgray", size = 6) +
      # annotate("text",x=as.POSIXlt("17:30",format = "%H:%M"), y = 10, label = "PM Peak", color = "darkgray", size = 3.5) +
geom_text(data = eb_text,mapping = aes(x=as.POSIXlt("23:50",format = "%H:%M"), y=eastbound+7.5, label = "EB"), color = "#5e3c99", size = 5, hjust = 0, fontface = 2) +
geom_text(data = wb_text,mapping = aes(x=as.POSIXlt("23:50",format = "%H:%M"), y=westbound-7.5, label = "WB"), color = "#e66101", size = 5, hjust = 0, fontface = 2) +
          geom_line(aes(y = eastbound), colour = "#5e3c99", size = 1.5) +
          geom_line(aes(y = westbound), colour = "#e66101", size = 1.5) +
          facet_grid(intersection_name ~ .) +
          theme_light() + 
          scale_x_datetime(breaks = lims, minor_breaks = lims, date_labels = "%H", limits = as.POSIXct(c("00:00","24:00"),format ="%H:%M")) +
          scale_y_continuous(breaks = c(0,200,400,600,800), minor_breaks = c(0,200,400,600,800)) +
          theme(legend.position = "bottom", 
                axis.text = element_text(size = 14), 
                axis.title = element_text(size = 14, face = "bold"),
                strip.text.x = element_text(size = 16),
                strip.text.y = element_text(size = 16),
                plot.title = element_text(size = 18, face = "bold"),
                plot.subtitle = element_text(size = 16)
                ) +
          labs(y = "Hourly Volume", x = "Time of Day", title = "King Street Transit Pilot - Vehicular Traffic", subtitle = "Baseline Hourly Weekday Volumes")

ggsave(filename = "king_baselines_hourly.png", plot = daily_plot, width = 12, height = 12, units = "in")

```
